#!/usr/bin/env node
// Generates src/assets.generated.ts from public/ so the Worker can serve the
// viewer without an assets binding (dashboard paste deploys). Runs automatically
// before `npm run dev`, `npm run deploy` and `npm run bundle`.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const workerDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = join(workerDir, 'public');
const outFile = join(workerDir, 'src', 'assets.generated.ts');

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
};

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const entries = walk(publicDir)
  .filter((f) => TYPES[extname(f)])
  .sort()
  .map((file) => {
    const body = readFileSync(file, 'utf8');
    const path = '/' + relative(publicDir, file).split('\\').join('/');
    const etag = '"' + createHash('sha256').update(body).digest('hex').slice(0, 16) + '"';
    return `  ${JSON.stringify(path)}: { type: ${JSON.stringify(TYPES[extname(file)])}, etag: ${JSON.stringify(etag)}, body: ${JSON.stringify(body)} },`;
  });

const source = `// Generated by scripts/inline-assets.mjs from public/ — do not edit by hand.
// Used only when the Worker has no ASSETS binding (single-file / dashboard deploys).
export interface InlineAsset {
  type: string;
  etag: string;
  body: string;
}

export const INLINE_ASSETS: Record<string, InlineAsset> = {
${entries.join('\n')}
};
`;

writeFileSync(outFile, source);
console.log(`inline-assets: wrote ${entries.length} files to ${relative(workerDir, outFile)}`);
